
[api]
  Address = "/ip4/0.0.0.0/tcp/39812"

[db]
  type = "mysql"

  [db.mysql]
    connMaxLifeTime = "1m0s"
    connectionString = "root:Root1234@(127.0.0.1:3306)/messager?parseTime=true&loc=Local"
    debug = false
    maxIdleConn = 10
    maxOpenConn = 10

  [db.sqlite]
    debug = false
    path = "./message.db"

[jwt]
  url = "http://127.0.0.1:8989"

[log]
  level = "info"
  path = "messager.log"

[messageService]
  skipProcessHead = false
  skipPushMessage = false
  tipsetFilePath = "./tipset.json"

[messageState]
  CleanupInterval = 86400
  DefaultExpiration = 259200
  backTime = 86400

[node]
  url = "/ip4/8.130.166.31/tcp/1234"
  token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"

[wallet]
  scanInterval = 10

[gateway]
  remoteEnable = false
  url = "/ip4/192.168.19.94/tcp/45132"
  token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"

  [gateway.cfg]
    RequestQueueSize = 30
    RequestTimeout = "5m0s"

[local]
  token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"
