
[address]
  remoteWalletSweepInterval = 10

[api]
  Address = "0.0.0.0:39812"

[db]
  type = "sqlite"

  [db.mysql]
    addr = ""
    connMaxLifeTime = "0s"
    maxIdleConn = 0
    maxOpenConn = 0
    name = ""
    pass = ""
    user = ""

  [db.sqlite]
    path = "./message.db"
    debug = false

[jwt]
    url= "http://127.0.0.1:8989"

[log]
  path = "messager.log"

[messageService]
  isProcessHead = true
  tipsetFilePath = "./tipset.txt"

[messageState]
  CleanupInterval = 86400
  DefaultExpiration = 259200
  backTime = 86400

[node]
    url = "/ip4/8.130.165.167/tcp/3453"
    token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.R6UZS9i6Y9vqAF-O4Z6y74uDK_8jT0M7OzqrrbNQ3II"
